
    <aside id="barra-cabecera">
        <p>Ejemplo de Ventanas en el navegador.</p>
        <p>Fronend js: Las ventanas son gestionadas por las clase Escritorio. La clase Ventana solo se encarga de la UI, cada uno tiene un controlador para el tipo de contenido. Se proporciona uno para ver una lista de datos y otro para ver un registro único, pero usted puede crear más. Los controladores heredan de Controlador, que se encarga de la mayoria de las tareas.</p>
        <p>Backend PHP: La clase Ventana se encarga de recuperar las ventanas el usuario, guardar y borrar. El contenido lo pide cada controladora js puesto que es especifico.</p>
    </aside>
